version: '3'

services:
  bot:
    build: .
    container_name: lobubble-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - PM2_PUBLIC_KEY=${PM2_PUBLIC_KEY}
      - PM2_SECRET_KEY=${PM2_SECRET_KEY}
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs 