services:
  - type: web
    name: lobubble-bot
    env: docker
    region: Frankfurt
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: NODE_ENV
        value: production
      - key: PM2_PUBLIC_KEY
        sync: false
        optional: true
      - key: PM2_SECRET_KEY
        sync: false
        optional: true
    healthCheckPath: /health
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 