services:
  - type: web
    name: lobubble-bot
    env: docker
    region: Frankfurt
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 